-- 코드를 입력하세요
SELECT A.OUTS_ANIMAL_ID AS ANIMAL_ID, A.OUTS_NAME AS NAME
FROM
(
    SELECT OUTS.ANIMAL_ID AS OUTS_ANIMAL_ID, OUTS.NAME AS OUTS_NAME
    FROM ANIMAL_OUTS OUTS
    LEFT JOIN ANIMAL_INS INS
    ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
    WHERE INS.ANIMAL_ID IS NULL
) A
ORDER BY A.OUTS_ANIMAL_ID